// ----------------------------------------------------------------------

export const fullName = [
  '부주의 - respond to high rate of non-target',
  '부주의 - respond to high rate of non-target',
  '충동성 - failed to control impulse of non-target',
  '충동성 - extremely liberal response style',
  '부주의 - loss of Sustained Attention',
  '부주의 - respond to high rate of non-target',
  '부주의 - respond to high rate of non-target',
  '부주의 - loss of Sustained Attention',
  '부주의 - loss of Sustained Attention',
  '부주의 - respond to high rate of non-target',
  '충동성 - extremely liberal response style',
  '부주의 - loss of Sustained Attention',
  '충동성 - failed to control impulse of non-target',
  '충동성 - extremely liberal response style',
  '충동성 - failed to control impulse of non-target',
  '부주의 - loss of Sustained Attention',
  '부주의 - respond to high rate of non-target',
  '충동성 - random response',
  '부주의 - respond to high rate of non-target',
  '부주의 - loss of Sustained Attention',
  '충동성 - random response',
  '충동성 - extremely liberal response style',
  '충동성 - extremely liberal response style',
  '충동성 - extremely liberal response style',
  '부주의 - respond to high rate of non-target',
  '충동성 - extremely liberal response style',
  '부주의 - respond to high rate of non-target',
  '충동성 - random response',
  '충동성 - extremely liberal response style',
  '부주의 - respond to high rate of non-target',
  '충동성 - anticipatory response',
  '충동성 - repeated response',
  '충동성 - extremely liberal response style',
  '충동성 - anticipatory response',
  '충동성 - extremely liberal response style',
  '충동성 - repeated response',
  '부주의 - respond to high rate of non-target',
  '충동성 - repeated response',
  '충동성 - anticipatory response',
  '부주의 - loss of Sustained Attention',
];
