// ----------------------------------------------------------------------

export const fullName = [
  '부주의 - respond to high rate of non-target',
  '부주의 - respond to high rate of non-target',
  '충동성 - failed to control impulse of non-target',
  '충동성 - extremely liberal response style',
  '부주의 - loss of Sustained Attention',
  '부주의 - respond to high rate of non-target',
  '부주의 - respond to high rate of non-target',
  '부주의 - loss of Sustained Attention',
  '부주의 - loss of Sustained Attention',
  '부주의 - respond to high rate of non-target',
  '충동성 - extremely liberal response style',
  '부주의 - loss of Sustained Attention',
  '충동성 - failed to control impulse of non-target',
  '충동성 - extremely liberal response style',
  '충동성 - failed to control impulse of non-target',
  '부주의 - loss of Sustained Attention',
  '부주의 - respond to high rate of non-target',
  '충동성 - random response',
  '부주의 - respond to high rate of non-target',
  '부주의 - loss of Sustained Attention',
  '충동성 - random response',
  '충동성 - extremely liberal response style',
  '충동성 - extremely liberal response style',
  '충동성 - extremely liberal response style',
  '부주의 - respond to high rate of non-target',
  '충동성 - extremely liberal response style',
  '부주의 - respond to high rate of non-target',
  '충동성 - random response',
  '충동성 - extremely liberal response style',
  '부주의 - respond to high rate of non-target',
  '충동성 - anticipatory response',
  '충동성 - repeated response',
  '충동성 - extremely liberal response style',
  '충동성 - anticipatory response',
  '충동성 - extremely liberal response style',
  '충동성 - repeated response',
  '부주의 - respond to high rate of non-target',
  '충동성 - repeated response',
  '충동성 - anticipatory response',
  '부주의 - loss of Sustained Attention',
];

export const firstName = [
  'Mossie',
  'David',
  'Ebba',
  'Chester',
  'Eula',
  'Jaren',
  'Boyd',
  'Brady',
  'Aida',
  'Anastasia',
  'Gregoria',
  'Julianne',
  'Ila',
  'Elyssa',
  'Lucio',
  'Lewis',
  'Jacinthe',
  'Molly',
  'Brown',
  'Fritz',
  'Keon',
  'Ella',
  'Ken',
  'Whitney',
  'Monte',
  'Rose',
  'Shana',
  'Devon',
  'Jaleel',
  'Laury',
  'Brooks',
  'Bruce',
  'Avery',
  'Esperanza',
  'Helene',
  'Heloise',
  'Elinor',
  'Adeline',
  'Haley',
  'Anabelle',
];

export const lastName = [
  'Carroll',
  'Simonis',
  'Yost',
  'Hand',
  'Emmerich',
  'Wilderman',
  'Howell',
  'Sporer',
  'Boehm',
  'Morar',
  'Koch',
  'Reynolds',
  'Padberg',
  'Watsica',
  'Upton',
  'Yundt',
  'Pfeffer',
  'Parker',
  'Zulauf',
  'Treutel',
  'McDermott',
  'McDermott',
  'Cruickshank',
  'Parisian',
  'Auer',
  'Turner',
  'Dooley',
  'Wiegand',
  'Abbott',
  'Wisoky',
  'Fahey',
  'Satterfield',
  'Bahringer',
  'Schulist',
  'Durgan',
  'Carroll',
  'Jones',
  'Leffler',
  'Gutkowski',
  'Homenick',
];
